apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: rhdhpai802-13
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhdhpai802-13
  name: rhdhpai802-13
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
